name: Service Request
description: A request for action, support, help for any internal operational or functional issue not immediately related to the capabilities of Timely itself.
title: "[Service Request]: "
labels: ["Type: Service Request", "Product: Timely"]
assignees:
  - lisarost
body:
  - type: markdown
    attributes:
      value: |
        Is this something we're doing for a customer, or is it internal?
  - type: dropdown
    id: sr-type
    attributes:
      label: Type of service request
      description: Is this something we're doing for a customer or lead, or is it internal?
      options:
        - External (for a customer/lead)
        - Internal (for ourselves)
    validations:
      required: true
  - type: input
    id: workspace-id
    attributes:
      label: Workspace ID
      description: If external, please input the workspace ID.
      placeholder: ex. 4301504
    validations:
      required: false
  - type: dropdown
    id: subscription status
    attributes:
      label: What is the subscription status of the workspace?
      options:
        - In Trial
        - Paying
        - Expired
  - type: textarea
    id: job-to-be-done
    attributes:
      label: Job to be done
      description: What needs to be done? Use numbered or bullet pointed steps if possible. The more detail, the faster we can get it done!
      placeholder: Use numbered or bullet pointed steps if possible. The more detail, the faster we can get it done!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
