---
name: Feature Request
about: Go to the [Portal](https://portal.timelyapp.com/tabs/2-considerations/submit-idea) to send feature requests.
---

## Do not add feature requests to Github directly.

To submit a feature request use the [Portal](https://portal.timelyapp.com/tabs/2-considerations/submit-idea) and send your feature request there. 

**Note:** Do **not** send feature requests directly into Github. 

