name: Bug Report
description: An aspect of our product(s) is not working the way it is designed/intended to function
title: "[Bug]: "
labels: ["Type: Bug"]
assignees:
  - lisarost
body:
  - type: markdown
    attributes:
      value: |
        ## About the bug
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what problem is being experienced.
      placeholder: Use numbered or bullet pointed steps if possible. The more detail, the faster we can get it done!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a clear and concise description of what problem is being experienced.
      placeholder: |
        1. _Go to..._
        2. _Click on..._
        3. _Scroll down to..._
        4. _See error..._
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what should happen in the Product (note if this is a missed case or new feature, please raise this [via Productboard](https://memory.slab.com/posts/i-want-to-xxq3acvx))
      placeholder:
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information / Links / Attachments
      placeholder: Put anything that will be helpful or required for us to address this issue
    validations:
      required: false
  - type: checkboxes
    id: impacted-platforms
    attributes:
      label: Which platforms/browsers are impacted?
      description: You may select more than one.
      options:
        - label: Web/Desktop
        - label: Chrome
        - label: Safari
        - label: Firefox
        - label: Edge
        - label: Other
        - label: iOS
        - label: Android
        - label: Memory App for macOS/Windows
  - type: markdown
    attributes:
      value: |
        ## Workspace information
  - type: input
    id: workspace-id
    attributes:
      label: Workspace ID (if applicable)
      description: Which workspace ID does the bug pertain to?
      placeholder: ex. 879312
    validations:
      required: false
  - type: dropdown
    id: subscription-status
    attributes:
      label: What is the subscription status of the workspace?
      options:
        - In Trial
        - Paying
        - Expired
  - type: input
    id: workspace-users
    attributes:
      label: Number of users on workspace
      description: Please input the number of users in the workspace. 
      placeholder: ex. 150
  - type: input
    id: workspace-mrr
    attributes:
      label: Workspace MRR
      description: Please input the MRR (current or potential) of the workspace. 
      placeholder: ex. 150
  - type: input
    id: user-id
    attributes:
      label: User ID (if applicable)
      description: Which user ID does the bug pertain to?
      placeholder: ex. 780101
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Urgency and impact
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency – how soon does this need to be fixed?
      options:
        - High (0–14 days)
        - Medium (15–30 days)
        - Low (30 days+)
    validations:
      required: false      
  - type: input
    id: impact
    attributes:
      label: Impact – what happens if we don't fix it within the timeframe?
      description: What will happen if this is not fixed in time?
      placeholder: ex. "person x is blocked from doing their job" 
    validations:
      required: false
        - type: markdown
    attributes:
      value: |
        ## Contact info
  - type: input
    id: contact-info
    attributes:
      label: Customer contact info
      description: How can the user be updated once the job is finished?
      placeholder: Intercom conversation link, e-mail etc.
    validations:
      required: false
