name: External Service Request
description: A request for action, support, help for a customer or lead. Not to be used for new feature requests. 
title: "[External Service Request]: "
labels: ["Type: External Service Request", "Product: Timely", "Type: Service Request"]
assignees:
  - lisarost
body:
  - type: markdown
    attributes:
      value: |
        An external service request is a job we're doing for a customer or potential customer (lead). Requests for new features should not be submitted here, send them through the [https://portal.timelyapp.com](portal) instead.
        ## Workspace details
  - type: input
    id: workspace-id
    attributes:
      label: Workspace ID
      description: Please input the workspace ID.
      placeholder: ex. 4301504
    validations:
      required: true
  - type: dropdown
    id: subscription-status
    attributes:
      label: What is the subscription status of the workspace?
      options:
        - In Trial
        - Paying
        - Expired
  - type: input
    id: workspace-users
    attributes:
      label: Number of users on workspace
      description: Please input the number of users in the workspace. 
      placeholder: ex. 150
    validations:
      required: true
  - type: input
    id: workspace-mrr
    attributes:
      label: Workspace MRR
      description: Please input the MRR (current or potential) of the workspace. 
      placeholder: ex. 150
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Urgency and impact
  - type: dropdown
    id: urgency
    attributes:
      label: Impact if not completed
      options:
        - High
        - Medium
        - Low
    validations:
      required: true      
  - type: input
    id: impact
    attributes:
      label: Impact if not completed
      description: What will happen if this is not completed in time?
      placeholder: ex. "the customer is very likely to churn" 
    validations:
      required: true      
  - type: textarea
    id: job-to-be-done
    attributes:
      label: Job to be done
      description: What needs to be done? Use numbered or bullet pointed steps if possible. The more detail, the faster we can get it done!
      placeholder: Use numbered or bullet pointed steps if possible. The more detail, the faster we can get it done!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
