name: Feature Request
description: Do not send feature requests directly into Github. Use the Portal.
body:
  - type: markdown
    attributes:
      value: |
        Requests for new features should not be submitted here, send them through the [Portal](https://portal.timelyapp.com) instead.
  - type: checkboxes
    id: understand
    attributes:
      label: I understand that I should not send feature requests in Github.
      description: Use the [Portal](https://portal.timelyapp.com) instead.
      options:
        - label: I will use the [Portal](https://portal.timelyapp.com) to send my feature request.
          required: true
